/* Generated by DNAsm → C compiler v2 */
#include "game_rt.h"

#define W (800)
#define H (600)
#define PAD_W (15)
#define PAD_H (90)
#define BALL_SZ (12)
#define BALL_SPD (5)
#define PAD_SPD (6)
#define WIN_SCORE (5)

static int pad1_y = 255;
static int pad2_y = 255;
static int ball_x = 394;
static int ball_y = 294;
static int ball_vx = 5;
static int ball_vy = 3;
static int score1 = 0;
static int score2 = 0;
static int state = 0;
static int scored_timer = 0;
static int winner = 0;

int update_play(void);
int update_scored(void);
int update_gameover(void);
int reset_ball(void);
int draw_title(void);
int draw_game(void);

int main(int argc, char *argv[]) {
    dna_rt_init("DNAPong - DNAOS", 800, 600);
    dna_rt_srand(dna_rt_ticks());
title_loop:
    if (dna_rt_poll()) goto end;
    draw_title();
    dna_rt_present();
    if (!dna_rt_key(DNA_KEY_SPACE)) goto title_loop;
    state = 1;
    reset_ball();
game_loop:
    if (dna_rt_poll()) goto end;
    if (!dna_rt_running()) goto end;
    if (state == 1) update_play();
    if (state == 2) update_scored();
    if (state == 3) update_gameover();
    draw_game();
    dna_rt_present();
    goto game_loop;
end:
    dna_rt_quit();
    return 0;
    return 0;
}

int update_play(void) {
    if (dna_rt_key(DNA_KEY_W)) {
        pad1_y = pad1_y - 6;
    }
    if (dna_rt_key(DNA_KEY_S)) {
        pad1_y = pad1_y + 6;
    }
    if (dna_rt_key(DNA_KEY_UP)) {
        pad2_y = pad2_y - 6;
    }
    if (dna_rt_key(DNA_KEY_DOWN)) {
        pad2_y = pad2_y + 6;
    }
    if (pad1_y < 0) {
        pad1_y = 0;
    }
    if (pad1_y > 510) {
        pad1_y = 510;
    }
    if (pad2_y < 0) {
        pad2_y = 0;
    }
    if (pad2_y > 510) {
        pad2_y = 510;
    }
    ball_x = ball_x + ball_vx;
    ball_y = ball_y + ball_vy;
    if (ball_y <= 0) {
        ball_vy = 0 - ball_vy;
    }
    if (ball_y >= 588) {
        ball_vy = 0 - ball_vy;
    }
    if (ball_x <= 20) {
    if (ball_y >= pad1_y) {
    if (ball_y <= pad1_y + 90) {
    ball_vx = 0 - ball_vx;
    ball_x = 20;
}
}
}
    if (ball_x >= 773) {
    if (ball_y >= pad2_y) {
    if (ball_y <= pad2_y + 90) {
    ball_vx = 0 - ball_vx;
    ball_x = 773;
}
}
}
    if (ball_x < 0) {
    score2 = score2 + 1;
    state = 2;
    scored_timer = 60;
    winner = 2;
    reset_ball();
}
    if (ball_x > 800) {
    score1 = score1 + 1;
    state = 2;
    scored_timer = 60;
    winner = 1;
    reset_ball();
}
}

int update_scored(void) {
    scored_timer = scored_timer - 1;
    if (scored_timer <= 0) {
    if (score1 >= 5) {
        state = 3;
    }
    if (score2 >= 5) {
        state = 3;
    }
    if (score1 < 5) {
    if (score2 < 5) {
        state = 1;
    }
}
}
}

int update_gameover(void) {
    if (dna_rt_key(DNA_KEY_SPACE)) {
    score1 = 0;
    score2 = 0;
    state = 1;
    reset_ball();
}
}

int reset_ball(void) {
    ball_x = 394;
    ball_y = 294;
    ball_vx = 5;
    ball_vy = 3;
    pad1_y = 255;
    pad2_y = 255;
}

int draw_title(void) {
    dna_rt_clear(10, 10, 30);
    dna_rt_text(280, 200, "DNAPONG", 0, 255, 128);
    dna_rt_text(220, 300, "PRESS SPACE TO START", 200, 200, 200);
    dna_rt_text(200, 400, "W/S: P1   UP/DOWN: P2", 150, 150, 150);
}

int draw_game(void) {
    dna_rt_clear(10, 10, 30);
    dna_rt_rect(395, 0, 2, 600, 50, 50, 50);
    dna_rt_rect(20, pad1_y, 15, 90, 0, 255, 128);
    dna_rt_rect(765, pad2_y, 15, 90, 255, 0, 200);
    dna_rt_rect(ball_x, ball_y, 12, 12, 255, 255, 255);
    if (score1 == 0) dna_rt_text(300, 30, "0", 255, 255, 255);
    if (score1 == 1) dna_rt_text(300, 30, "1", 255, 255, 255);
    if (score1 == 2) dna_rt_text(300, 30, "2", 255, 255, 255);
    if (score1 == 3) dna_rt_text(300, 30, "3", 255, 255, 255);
    if (score1 == 4) dna_rt_text(300, 30, "4", 255, 255, 255);
    if (score1 == 5) dna_rt_text(300, 30, "5", 255, 255, 255);
    if (score2 == 0) dna_rt_text(480, 30, "0", 255, 255, 255);
    if (score2 == 1) dna_rt_text(480, 30, "1", 255, 255, 255);
    if (score2 == 2) dna_rt_text(480, 30, "2", 255, 255, 255);
    if (score2 == 3) dna_rt_text(480, 30, "3", 255, 255, 255);
    if (score2 == 4) dna_rt_text(480, 30, "4", 255, 255, 255);
    if (score2 == 5) dna_rt_text(480, 30, "5", 255, 255, 255);
    if (state == 2) dna_rt_text(340, 280, "SCORE!", 255, 255, 0);
    if (state == 3) {
    if (winner == 1) dna_rt_text(240, 260, "PLAYER 1 WINS!", 0, 255, 128);
    if (winner == 2) dna_rt_text(240, 260, "PLAYER 2 WINS!", 255, 0, 200);
    dna_rt_text(230, 320, "PRESS SPACE TO RESTART", 200, 200, 200);
}
}
